module.exports = {
  API_NAME: 'subscriptions_API',
  CUIT_CRONISTA: '30500090029',

  AFIP_CONCEPTO_PRODUCTO: 1, //1=productos, 2=servicios, 3=ambos
  AFIP_DOC_TIPO_CUIT: 80, //80 -cuit   86 - cuil   96-dni
  AFIP_DOC_TIPO_CUIL: 86,
  AFIP_MON_ID: 'PES',
  AFIP_MON_COTIZ: 1,
  AFIP_IIBB_ID: 2,
  AFIP_IIBB_DESCRIPTION: 'IIBB CABA',
  DEFAULT_IVA: 10.5,

  RECEIPT_FACTURA_A: 1,
  RECEIPT_ND_A: 2,
  RECEIPT_ND_A_INTERNA: 1002,
  RECEIPT_NC_A: 3,
  RECEIPT_NC_A_INTERNA: 1003,
  RECEIPT_FACTURA_B: 6,
  RECEIPT_ND_B: 7,
  RECEIPT_ND_B_INTERNA: 1007,
  RECEIPT_NC_B: 8,
  RECEIPT_NC_B_INTERNA: 1008,

  ADDRESS_TYPE_LEGAL: 1,
  COLLECTION_METHOD_MERCADOPAGO: 6,
  DISTRIBUTION_STATE_INITIAL: 0,
  PERSON_TYPE_PERSONA_FISICA: 1,
  SELLING_CHANNEL_ADMIN: 0,
  SELLING_CHANNEL_CALLCENTER: 3,
  SELLING_CHANNEL_ECOMMERCE: 4,
  BILLING_PERDIOD_MONTHLY: 1,
  BILLING_PERDIOD_ANNUAL: 2,
  BILLING_PERIOD_QUARTERLY: 3,
  BILLING_PERIOD_BIANNUAL: 4,
  TAX_CONDITION_SIN_CONDICION_IMPOSITIVA: 0,
  TAX_CONDITION_CONSUMIDOR_FINAL: 3
};
